### ISSUE TITLE
add new demo

### ISSUE THREAD

**Issue by JunchuanYu** [gradio-app/world-of-demos#16]
Hey there! 

I've just pushed a Pull Request to the gradio-app/awesome-demos repository, and I'd really appreciate it if you could take a look at the two new demos I've added. I think they'll be a great addition to the community, especially for those working in remote sensing.

By the way, I'm also working on a tutorial to help newcomers get the hang of Gradio. It's full of practical examples and can be found at [this link](https://junchuanyu.github.io/Building_Interactive_Web_APP_with_Gradio/). I hope it'll make learning Gradio a bit easier and more fun.

Finally, a big shoutout to the Gradio team – this project is just awesome, and it's been a game-changer for building interactive web apps. Thanks for creating such a cool tool!

Junchuan Yu

**Comment by abidlabs** [comment]
Thanks @junchuanyu! I'll review the PR shortly. 

And the tutorial looks really really nice. I'll share with the team. Is it ok if I share on social media as well?

**Comment by JunchuanYu** [comment]
ok，thank you

**Comment by JunchuanYu** [comment]
@abidlabs
